---
abstract: 'Parse Excel Spreadsheets using xlhtml'
author:
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Spreadsheet::WriteExcel: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Spreadsheet-ParseExcel_XLHTML
no_index:
  directory:
    - inc
    - t
provides:
  Spreadsheet::ParseExcel_XLHTML:
    file: lib/Spreadsheet/ParseExcel_XLHTML.pm
    version: 0.04
requires:
  HTML::Entities: 0
  Spreadsheet::ParseExcel: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rkitover/spreadsheet-parseexcel-xlhtml.git
version: 0.04
